package com.prasad.agentic_software_engineer.audit;

public enum AuditEventType {
    WORKFLOW_CREATED,
    WORKFLOW_STARTED,
    TASK_STARTED,
    AGENT_OUTPUT_GENERATED,
    TASK_SUCCEEDED,
    TASK_FAILED,
    CLARIFICATION_REQUIRED,
    CLARIFICATION_SUBMITTED,
    APPROVAL_REQUIRED,
    RELEASE_APPROVED,
    RELEASE_REJECTED,
    SAFE_STOPPED,
    VALIDATION_ATTEMPT_STARTED,
    VALIDATION_ATTEMPT_SUCCEEDED,
    VALIDATION_ATTEMPT_FAILED,
    REPAIR_STARTED,
    WORKFLOW_COMPLETED,
    WORKFLOW_FAILED
}
